# Kit Configuration
kit:
  name: shield

# Build Configuration
build:
  fetch_depth: 0  # Need full history for tags

# Environment Configuration
environments:
  ci-testing:
    deploy_env: ci-vsphere-baseline
    ci_root: ${{ github.workspace }}/ci
    github_workspace: ${{ github.workspace }}

# Infrastructure Configuration
infra:
  default_iaas: vsphere

# Tools Configuration
tools:
  go:
    version: 1.23.5
    platform: linux-amd64

# Test Configuration
test:
  spec:
    directory: spec
    runner: ginkgo
    parallel: true
    results_dir: spec-check
    diff_prefix: diff-

# Release Configuration
release:
  labels: release
  base_branch: main
  pr_title_prefix: Release v