name: Release Pipeline

on:
  push:
    branches: [develop, main]
    paths-ignore: ['ci/**']
  pull_request:
    branches: [develop]
    paths-ignore: ['ci/**']
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  load-env:
    runs-on: ubuntu-latest
    outputs:
      env_vars: ${{ steps.set-env.outputs.env_vars }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Load Environment Variables
        id: set-env
        run: |
          # Load common environment variables
          if [ -f .github/env/common.env ]; then
            while IFS= read -r line || [ -n "$line" ]; do
              # Skip comments and empty lines
              if [[ $line =~ ^[^#].+=.+ ]]; then
                echo "$line" >> $GITHUB_ENV
                # Also add to output for other jobs
                echo "$line" >> $GITHUB_OUTPUT
              fi
            done < .github/env/common.env
          fi
          
          # Determine environment file based on context
          ENV_FILE=".github/env/development.env"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENV_FILE=".github/env/production.env"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ENV_FILE=".github/env/testing.env"
          fi
          
          # Load environment-specific variables
          if [ -f "$ENV_FILE" ]; then
            while IFS= read -r line || [ -n "$line" ]; do
              if [[ $line =~ ^[^#].+=.+ ]]; then
                echo "$line" >> $GITHUB_ENV
                echo "$line" >> $GITHUB_OUTPUT
              fi
            done < "$ENV_FILE"
          fi

  build-kit:
    needs: load-env
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.BUILD_FETCH_DEPTH }}
          
      - id: version
        uses: ./.github/actions/version-manager
        with:
          bump_type: ${{ inputs.version_bump || env.BUILD_DEFAULT_VERSION_BUMP }}
          
      - name: Push version change
        run: |
          git push origin HEAD
          git tag "v${{ steps.version.outputs.new_version }}"
          git push origin "v${{ steps.version.outputs.new_version }}"
          
      - name: Build Kit
        env:
          GENESIS_SECRETS_BASE: ${{ secrets.SECRETS_BASE }}
          GENESIS_SECRETS_TOKEN: ${{ secrets.SECRETS_TOKEN }}
          GENESIS_SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
          BOSH_CLIENT: ${{ secrets.BOSH_CLIENT }}
          BOSH_CLIENT_SECRET: ${{ secrets.BOSH_CLIENT_SECRET }}
          BOSH_ENVIRONMENT: ${{ secrets.BOSH_ENVIRONMENT }}
          BOSH_CA_CERT: ${{ secrets.BOSH_CA_CERT }}
        run: |
          sudo chmod -R a+rwx ./*
          ./ci/scripts/ensure-tools.sh
          VERSION="${{ steps.version.outputs.new_version }}"
          genesis compile-kit --force -v "${KIT_VERSION}" -n "${KIT_NAME}"
          
      - uses: actions/upload-artifact@v4
        with:
          name: kit-build
          path: ${{ KIT_NAME }}-${{ steps.version.outputs.new_version }}.tar.gz

  spec-tests:
    needs: [load-env, build-kit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: kit-build
          
      - name: Run Spec Tests
        env:
          GENESIS_SECRETS_BASE: ${{ secrets.SECRETS_BASE }}
          GENESIS_SECRETS_TOKEN: ${{ secrets.SECRETS_TOKEN }}
          GENESIS_SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
        run: |
          sudo chmod -R a+rwx ./*
          ./ci/scripts/ensure-tools.sh

          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go${{ env.GO_VERSION }}.${{ env.GO_PLATFORM }}.tar.gz
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          export PATH=$PATH:~/go/bin
          
          cd ${{ env.TEST_SPEC_DIR }}
          ${{ env.TEST_SPEC_RUNNER }} ${{ env.TEST_SPEC_PARALLEL == 'true' && '-p' || '' }} .

  spec-check:
    needs: [load-env, build-kit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.BUILD_FETCH_DEPTH }}
          
      # ... rest of the spec-check job remains the same but using env.* instead of vars.*

  deploy:
    needs: [load-env, spec-tests, spec-check]
    runs-on: ubuntu-latest
    environment: ci-testing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: kit-build
          
      - name: Set up Infrastructure
        uses: ./.github/actions/setup-infra
        with:
          iaas: ${{ env.INFRA_DEFAULT_IAAS }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          gcp_service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          vsphere_username: ${{ secrets.VSPHERE_USERNAME }}
          vsphere_password: ${{ secrets.VSPHERE_PASSWORD }}
          
      - name: Deploy and Test
        env:
          DEPLOY_ENV: ${{ env.DEPLOY_ENV }}
          CI_ROOT: ${{ env.CI_ROOT }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GENESIS_SECRETS_BASE: ${{ secrets.SECRETS_BASE }}
          GENESIS_SECRETS_TOKEN: ${{ secrets.SECRETS_TOKEN }}
          GENESIS_SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
          BOSH_CLIENT: ${{ secrets.BOSH_CLIENT }}
          BOSH_CLIENT_SECRET: ${{ secrets.BOSH_CLIENT_SECRET }}
          BOSH_ENVIRONMENT: ${{ secrets.BOSH_ENVIRONMENT }}
          BOSH_CA_CERT: ${{ secrets.BOSH_CA_CERT }}
          SECRETS_SEED_DATA: ${{ secrets.SECRETS_SEED_DATA }}
        run: |
          sudo chmod -R a+rwx ./**
          ./ci/scripts/ensure-tools.sh
          ./ci/scripts/test-deployment.sh

  prepare-release:
    if: github.ref == 'refs/heads/develop' && github.event_name != 'pull_request'
    needs: [load-env, deploy, build-kit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: spec-diffs
          
      - name: Generate Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./ci/scripts/generate-release-notes.sh \
            "${{ needs.build-kit.outputs.version }}" \
            "${{ github.workspace }}/previous-tag" \
            "release-notes.md"
            
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ needs.build-kit.outputs.version }}
          title: ${{ env.RELEASE_PR_TITLE_PREFIX }}${{ needs.build-kit.outputs.version }}
          body: |
            Release preparation for version ${{ needs.build-kit.outputs.version }}
            
            Generated release notes and spec diffs attached.
          labels: ${{ env.RELEASE_LABELS }}
          base: ${{ env.RELEASE_BASE_BRANCH }}

  release:
    if: github.ref == 'refs/heads/main'
    needs: [load-env, deploy, build-kit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: kit-build
          
      - name: Download Spec Diffs
        uses: actions/download-artifact@v4
        with:
          name: spec-diffs
          path: spec-diffs
          
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build-kit.outputs.version }}
          name: v${{ needs.build-kit.outputs.version }}
          body_path: release-notes/release-notes.md
          files: |
            *.tar.gz
            spec-diffs/*
          prerelease: false
          
      - name: Notify Success
        if: success()
        uses: ./.github/actions/notify
        with:
          message: "Successfully released v${{ needs.build-kit.outputs.version }}"
          status: success